## Quarto file for the basic-report profile
project:
  title: "No Fairness without Awareness"
  output-dir: _basic-report

## Format settings
format:
  html:
    # Theme settings
    theme: 
    - "brand/scss/basic-report.scss"
    
## Execute settings
execute:
  freeze: auto

# Book settings
book:
  title: "No Fairness without Awareness"
  chapters:
    - index.qmd
    
    - part: "Analyse"
      chapters:
        - ch1-introduction.qmd
        - ch2-equity.qmd
        - ch3-factors.qmd
        - ch5-references.qmd
  appendices:
    - x-a-appendix-abbreviations.qmd

